### PR TITLE
Ignore dist and docs for features, force add on deploy script

### PR DESCRIPTION
**Pull request by athurman**
- I had to change the gulp task name on line 362 from `gulp.task('commit-build', function() {` to `gulp.task('commit-deploy', function() {` in order to get it to work, as well as separate out the force add of the dist and docs folders into its own commit in order to get it to work.

### CODE REVIEW

**Comment by eanplatter** [comment]
Oh yay it works!!

　　　　　　　　　　　 　 ∧__∧
　　　　　　　　　　　 　( ͡° ͜ʖ ͡°)
　　　　　　　　　　　　⊂　　つ
　　　　　　　　　　　　　(つ ﾉ
　　　　　　　　　　　　　 (ノ
　　　　　＼　　　　　　☆
　　　　　　　　　　　　　|　　　　　☆
　　　　　　　　　　(⌒ ⌒ヽ　　　/
　　　　＼　　（´⌒　　⌒　　⌒ヾ　　　／
　　　　　 （’⌒　;　⌒　　　::⌒　　）
　　　　　（´　　　　　）　　　　　:::　）　／
　　☆─　（´⌒;:　　　　::⌒`）　:;　　）
　　　　　（⌒::　　　::　　　　　::⌒　）
　　 　／　（　　　　ゝ　　ヾ　丶　　ソ　─

**Comment by levithomason** [comment]
@eanplatter I can't get it to work, how did you test it?

**Comment by athurman** [comment]
This is **officially** ready for review @levithomason

**Comment by levithomason** [comment]
o　　　o
　　　　o　＼　　o　　／　o　　　　
　　　o　　 o　　 l　　　o　　 o
　　　　　o-　　 ○　　-o                            <-- fireworks!
　　　o　　 o　　 l　　　o　　 o　　　　　　　
　　　　o　　　/ o　　　　o
　　　　　／ o　　　o　＼　　　　

　　　　　　　　 （
　　　　　　　　　）
　　　　　　　　 （
　　　　　　　　 （
　　　　　　　　　）
　　　　　　　　 （

**Pull request merged**
